services:
  planriean-api-fnlp:
    image: ponlawatp/planriean-api-fnlp:latest
    restart: unless-stopped
    deploy:
      replicas: 5
    extra_hosts:
      - "planriean-db:100.111.100.50"
    networks:
      - nginx_planriean

networks:
  nginx_planriean:
    external: true
